spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: zifeichat
  datasource:
    url: jdbc:mysql://${zifeichat.mysql.ip}:${zifeichat.mysql.port}/${zifeichat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${zifeichat.mysql.username}
    password: ${zifeichat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${zifeichat.redis.host}
    # Redis服务器端口号
    port: ${zifeichat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${zifeichat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${zifeichat.wx.callback}
    configs:
      - appId: ${zifeichat.wx.appId} # 第一个公众号的appid
        secret: ${zifeichat.wx.secret} # 公众号的appsecret
        token: ${zifeichat.wx.token} # 接口配置里的Token值
#        aesKey: ${zifeichat.wx.aesKey} # 接口配置里的EncodingAESKey值    